version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - depguard
    - embeddedstructfieldcheck
    - exhaustruct
    - funcorder
    - ireturn
    - nlreturn
    - noinlineerr
    - gochecknoglobals
    - paralleltest
    - revive
    - tagalign
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb*
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb*
